### ISSUE TITLE
🍹  Pyatnichnaya host functionality  

### ISSUE THREAD

**Issue by stpnvntn** [yrutkouski/smg-tussen#1]
Hi!

✨ I'm really like that you start working on smg tussen ✨

The only thing I miss right now is "who is `pyatnichnaya` host" functionality.

Could you please start working on a solution this week?

**Comment by yrutkouski** [comment]
https://github.com/yrutkouski/smg-tussen/commit/a9a8674242ea0f7f9c6939bd4e822ddafa18b5ac

please check 

🍻
